import { Car, Home, Smartphone, Gamepad2, Shirt, Dumbbell, Book, Palette, Camera, Star, DollarSign, Package } from "lucide-react"
import type { CategoryWithRequirements, ItemCondition, SellingTip, Language, Location } from "./types"

export const CURRENCIES = [
  { code: 'TZS', name: 'Tanzanian Shilling', flag: '🇹🇿' },
  { code: 'KES', name: 'Kenyan Shilling', flag: '🇰🇪' },
  { code: 'UGX', name: 'Ugandan Shilling', flag: '🇺🇬' },
  { code: 'USD', name: 'US Dollar', flag: '��🇸' },
] as const

export const CAROUSEL_ITEMS = [
  {
    id: 1,
    category: "Vehicles",
    image: "/images/hero-automotive.jpg",
    title: "Premium Vehicles for Expats",
  },
  {
    id: 2,
    category: "Furniture",
    image: "/images/hero-furniture.jpg",
    title: "Luxury Home Furniture",
  },
  {
    id: 3,
    category: "Electronics",
    image: "/images/hero-electronics.jpg",
    title: "Latest Tech & Electronics",
  },
  {
    id: 4,
    category: "Games & Toys",
    image: "/images/hero-gaming.jpg",
    title: "Games & Entertainment",
  },
] as const

export const CATEGORIES = [
  {
    id: 1,
    name: "Automotive",
    icon: Car,
    badge: "Premium",
    badgeColor: "bg-amber-500",
    count: "2,847 items",
    slug: "automotive",
  },
  {
    id: 2,
    name: "Home & Furniture",
    icon: Home,
    badge: "Luxury",
    badgeColor: "bg-orange-600",
    count: "5,234 items",
    slug: "home-furniture",
  },
  {
    id: 3,
    name: "Electronics & Tech",
    icon: Smartphone,
    badge: "Expert",
    badgeColor: "bg-cyan-500",
    count: "8,921 items",
    slug: "electronics-tech",
  },
  {
    id: 4,
    name: "Games & Toys",
    icon: Gamepad2,
    badge: "Trending",
    badgeColor: "bg-green-500",
    count: "1,456 items",
    slug: "games-toys",
  },
  {
    id: 5,
    name: "Fashion & Style",
    icon: Shirt,
    badge: "Curated",
    badgeColor: "bg-purple-500",
    count: "3,678 items",
    slug: "fashion-style",
  },
  {
    id: 6,
    name: "Fitness & Sports",
    icon: Dumbbell,
    badge: "Premium",
    badgeColor: "bg-amber-500",
    count: "987 items",
    slug: "fitness-sports",
  },
  {
    id: 7,
    name: "Books & Media",
    icon: Book,
    badge: "Rare",
    badgeColor: "bg-red-500",
    count: "2,134 items",
    slug: "books-media",
  },
  {
    id: 8,
    name: "Arts & Crafts",
    icon: Palette,
    badge: "Local",
    badgeColor: "bg-blue-500",
    count: "756 items",
    slug: "arts-crafts",
  },
] as const

export const TRUST_INDICATORS = [
  { text: "Verified Sellers", color: "bg-green-400" },
  { text: "Secure Payments", color: "bg-green-400" },
  { text: "Regional Shipping", color: "bg-green-400" },
  { text: "Community Trusted", color: "bg-green-400" },
] as const

export const DEFAULT_USER = {
  name: "Dr. Sarah M.",
  email: "sarah.mitchell@un.org",
  avatar: "/images/seller-avatar-1.jpg",
} as const

export const featuredItems = [
  // First Row - Premium Items
  {
    id: 1,
    title: 'MacBook Pro 14" M2',
    price: "3,500,000 TZS",
    originalPrice: "4,200,000 TZS",
    image: "/images/macbook-pro.jpg",
    seller: "TechExpat Dar",
    rating: 4.9,
    reviews: 88,
    location: "Dar es Salaam, TZ",
    isVerified: true,
    isPremium: true,
    premiumLabel: "Expert Seller",
  },
  {
    id: 2,
    title: "Toyota Rav4 2021 - Expat Owned",
    price: "85,000,000 TZS",
    originalPrice: "95,000,000 TZS",
    image: "/images/bmw-x5.jpg",
    seller: "AutoExpat TZ",
    rating: 4.8,
    reviews: 45,
    location: "Dar es Salaam, TZ",
    isVerified: true,
    isPremium: true,
    premiumLabel: "Premium",
  },
  {
    id: 3,
    title: "Designer Sofa Set - Imported",
    price: "2,800,000 TZS",
    originalPrice: "3,500,000 TZS",
    image: "/images/italian-sofa.jpg",
    seller: "HomeDecor TZ",
    rating: 4.7,
    reviews: 56,
    location: "Arusha, TZ",
    isVerified: true,
    isPremium: false,
  },
  {
    id: 4,
    title: "PlayStation 5 + Games Bundle",
    price: "1,800,000 TZS",
    originalPrice: "2,200,000 TZS",
    image: "/images/playstation-5.jpg",
    seller: "GameHub TZ",
    rating: 4.9,
    reviews: 150,
    location: "Nairobi, KE",
    isVerified: true,
    isPremium: false,
  },
  // Second Row - More Items
  {
    id: 5,
    title: "Samsung 65\" 4K TV",
    price: "2,500,000 TZS",
    originalPrice: "3,000,000 TZS",
    image: "/images/rolex-watch.jpg",
    seller: "Electronics TZ",
    rating: 4.9,
    reviews: 78,
    location: "Dar es Salaam, TZ",
    isVerified: true,
    isPremium: true,
    premiumLabel: "Top Rated",
  },
  {
    id: 6,
    title: "Toyota Land Cruiser Prado 2018",
    price: "150,000,000 TZS",
    originalPrice: "165,000,000 TZS",
    image: "/images/mercedes-c-class.jpg",
    seller: "Safari Motors",
    rating: 4.8,
    reviews: 32,
    location: "Arusha, TZ",
    isVerified: true,
    isPremium: true,
    premiumLabel: "4x4 Ready",
  },
  {
    id: 7,
    title: "Herman Miller Aeron Chair",
    price: "1,500,000 TZS",
    originalPrice: "2,000,000 TZS",
    image: "/images/herman-miller-chair.jpg",
    seller: "OfficeSolutions KE",
    rating: 4.6,
    reviews: 92,
    location: "Nairobi, KE",
    isVerified: true,
    isPremium: false,
  },
  {
    id: 8,
    title: "Canon EOS R5 + Lens Kit",
    price: "7,000,000 TZS",
    originalPrice: "8,500,000 TZS",
    image: "/images/canon-camera.jpg",
    seller: "PhotoPro Expat",
    rating: 4.9,
    reviews: 156,
    location: "Kampala, UG",
    isVerified: true,
    isPremium: false,
  },
  // Third Row - Mixed Items
  {
    id: 9,
    title: "iPad Pro 11\" M2 + Accessories",
    price: "2,800,000 TZS",
    originalPrice: "3,400,000 TZS",
    image: "/images/ipad-pro.jpg",
    seller: "TechHub KE",
    rating: 4.8,
    reviews: 203,
    location: "Nairobi, KE",
    isVerified: true,
    isPremium: true,
    premiumLabel: "Latest Model",
  },
  {
    id: 10,
    title: "Vintage Zanzibar Chest",
    price: "1,200,000 TZS",
    originalPrice: "1,500,000 TZS",
    image: "/images/harley-davidson.jpg",
    seller: "Antiques TZ",
    rating: 4.7,
    reviews: 34,
    location: "Zanzibar, TZ",
    isVerified: true,
    isPremium: true,
    premiumLabel: "Collector's Item",
  },
  {
    id: 11,
    title: "KitchenAid Stand Mixer Pro",
    price: "800,000 TZS",
    originalPrice: "1,000,000 TZS",
    image: "/images/kitchenaid-mixer.jpg",
    seller: "CulinaryWorld",
    rating: 4.6,
    reviews: 128,
    location: "Dar es Salaam, TZ",
    isVerified: true,
    isPremium: false,
  },
  {
    id: 12,
    title: "Mountain Bike - Full Suspension",
    price: "950,000 TZS",
    originalPrice: "1,200,000 TZS",
    image: "/images/nintendo-switch.jpg",
    seller: "AdventureBikes UG",
    rating: 4.9,
    reviews: 187,
    location: "Kampala, UG",
    isVerified: true,
    isPremium: false,
  },
]

export const SELLING_CATEGORIES: CategoryWithRequirements[] = [
  { value: "automotive", label: "Automotive", imageRequirements: ["front", "left", "right", "interior"] },
  { value: "electronics", label: "Electronics & Tech", imageRequirements: ["main", "screen", "ports"] },
  { value: "furniture", label: "Home & Furniture", imageRequirements: ["main", "detail", "condition"] },
  { value: "appliances", label: "Appliances", imageRequirements: ["main", "label", "condition"] },
  { value: "books", label: "Books & Media", imageRequirements: ["cover", "spine"] },
  { value: "clothing", label: "Clothing & Accessories", imageRequirements: ["main", "detail"] },
  { value: "sports", label: "Sports & Fitness", imageRequirements: ["main", "condition"] },
  { value: "other", label: "Other", imageRequirements: ["main"] },
] as const

export const ITEM_CONDITIONS: ItemCondition[] = [
  { value: "new", label: "New", description: "Brand new, never used" },
  { value: "like-new", label: "Like New", description: "Used once or twice, excellent condition" },
  { value: "excellent", label: "Excellent", description: "Lightly used, very good condition" },
  { value: "very-good", label: "Very Good", description: "Used with minor signs of wear" },
  { value: "good", label: "Good", description: "Used with normal signs of wear" },
  { value: "fair", label: "Fair", description: "Heavily used but functional" },
] as const

export const SELLING_TIPS: SellingTip[] = [
  {
    icon: Camera,
    title: "Take Great Photos",
    description: "Use natural lighting and multiple angles. High-quality photos get 3x more views.",
  },
  {
    icon: Star,
    title: "Write Detailed Descriptions",
    description: "Include brand, model, condition, and reason for selling. Be honest and thorough.",
  },
  {
    icon: DollarSign,
    title: "Price Competitively",
    description: "Research similar items and price fairly. Consider the condition and market demand.",
  },
  {
    icon: Package,
    title: "Fast Response",
    description: "Reply to inquiries quickly. Responsive sellers are more likely to make sales.",
  },
] as const

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "zh", name: "Mandarin", nativeName: "中文" },
] as const

export const EXPAT_LOCATIONS: Location[] = [
  { value: "dubai", label: "Dubai, UAE", country: "United Arab Emirates" },
  { value: "singapore", label: "Singapore", country: "Singapore" },
  { value: "london", label: "London, UK", country: "United Kingdom" },
  { value: "toronto", label: "Toronto, CA", country: "Canada" },
  { value: "dar-es-salaam", label: "Dar es Salaam, TZ", country: "Tanzania" },
  { value: "nairobi", label: "Nairobi, KE", country: "Kenya" },
  { value: "kampala", label: "Kampala, UG", country: "Uganda" },
  { value: "arusha", label: "Arusha, TZ", country: "Tanzania" },
  { value: "zanzibar", label: "Zanzibar, TZ", country: "Tanzania" },
] as const

export const SORT_OPTIONS = [
  { value: "relevance", label: "Most Relevant" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "newest", label: "Newest First" },
  { value: "rating", label: "Highest Rated" },
] as const

export const STATUS_COLORS = {
  active: "bg-green-100 text-green-800",
  sold: "bg-blue-100 text-blue-800",
  pending: "bg-yellow-100 text-yellow-800",
  draft: "bg-gray-100 text-gray-800",
  expired: "bg-red-100 text-red-800",
} as const

export const IMAGE_TYPE_LABELS = {
  front: "Front View",
  left: "Left Side",
  right: "Right Side",
  interior: "Interior",
  main: "Main Photo",
  screen: "Screen/Display",
  ports: "Ports/Connections",
  detail: "Detail Shot",
  condition: "Condition",
  label: "Product Label",
  cover: "Cover/Front",
  spine: "Spine/Back",
} as const 